# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "private_network", type: "dhcp"

  config.vm.define "database", primary: true do |server|
    server.vm.network "private_network", ip: "192.168.20.2"
    server.vm.network "forwarded_port", guest: 9999, host: 9998
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
    server.vm.hostname = "database"
    server.vm.provision "shell", inline: <<-SHELL
      echo "Hej from server one!" > /var/www/html/index.html
    SHELL
  end

  config.vm.define "webserver" do |client|
    client.vm.network "private_network", ip: "192.168.20.3"
    client.vm.network "forwarded_port", guest: 9999, host: 9999
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
    client.vm.hostname = "webserver"
    client.vm.provision "shell", inline: <<-SHELL
      echo "Hej from server 2!" > /var/www/html/index.html
    SHELL
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update
    sudo apt-get -y install apache2
  SHELL
end